/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include <math.h>

#include "api_types.h"
#include <thrift/c_glib/thrift.h>

enum _ReportEventProperties
{
  PROP_REPORT_EVENT_0,
  PROP_REPORT_EVENT_EVENT_ID,
  PROP_REPORT_EVENT_EVENT_LIB_ID,
  PROP_REPORT_EVENT_TIME_NOW,
  PROP_REPORT_EVENT_EVENT_INFO,
  PROP_REPORT_EVENT_EVENT_DESC,
  PROP_REPORT_EVENT_MAC,
  PROP_REPORT_EVENT_PEER_MAC,
  PROP_REPORT_EVENT_PROBER_MAC,
  PROP_REPORT_EVENT_PROBER_IP,
  PROP_REPORT_EVENT_PROBER_PORT,
  PROP_REPORT_EVENT_CHANNEL,
  PROP_REPORT_EVENT_SIGNAL,
  PROP_REPORT_EVENT_BAND,
  PROP_REPORT_EVENT_SSID,
  PROP_REPORT_EVENT_BSSID
};

/* reads a report_event object */
static gint32
report_event_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  ReportEvent * this_object = REPORT_EVENT(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_I16)
        {
          if ((ret = thrift_protocol_read_i16 (protocol, &this_object->eventId, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_eventId = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 2:
        if (ftype == T_I16)
        {
          if ((ret = thrift_protocol_read_i16 (protocol, &this_object->eventLibId, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_eventLibId = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 3:
        if (ftype == T_I64)
        {
          if ((ret = thrift_protocol_read_i64 (protocol, &this_object->timeNow, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_timeNow = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 4:
        if (ftype == T_STRING)
        {
          if (this_object->eventInfo != NULL)
          {
            g_free(this_object->eventInfo);
            this_object->eventInfo = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->eventInfo, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_eventInfo = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 5:
        if (ftype == T_STRING)
        {
          if (this_object->eventDesc != NULL)
          {
            g_free(this_object->eventDesc);
            this_object->eventDesc = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->eventDesc, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_eventDesc = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 6:
        if (ftype == T_STRING)
        {
          if (this_object->mac != NULL)
          {
            g_free(this_object->mac);
            this_object->mac = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->mac, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_mac = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 7:
        if (ftype == T_STRING)
        {
          if (this_object->peerMac != NULL)
          {
            g_free(this_object->peerMac);
            this_object->peerMac = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->peerMac, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_peerMac = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 8:
        if (ftype == T_STRING)
        {
          if (this_object->proberMac != NULL)
          {
            g_free(this_object->proberMac);
            this_object->proberMac = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->proberMac, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_proberMac = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 9:
        if (ftype == T_STRING)
        {
          if (this_object->proberIp != NULL)
          {
            g_free(this_object->proberIp);
            this_object->proberIp = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->proberIp, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_proberIp = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 10:
        if (ftype == T_STRING)
        {
          if (this_object->proberPort != NULL)
          {
            g_free(this_object->proberPort);
            this_object->proberPort = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->proberPort, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_proberPort = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 11:
        if (ftype == T_I16)
        {
          if ((ret = thrift_protocol_read_i16 (protocol, &this_object->channel, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_channel = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 12:
        if (ftype == T_I16)
        {
          if ((ret = thrift_protocol_read_i16 (protocol, &this_object->signal, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_signal = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 13:
        if (ftype == T_I16)
        {
          if ((ret = thrift_protocol_read_i16 (protocol, &this_object->band, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_band = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 14:
        if (ftype == T_STRING)
        {
          if (this_object->ssid != NULL)
          {
            g_free(this_object->ssid);
            this_object->ssid = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->ssid, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_ssid = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 15:
        if (ftype == T_STRING)
        {
          if (this_object->bssid != NULL)
          {
            g_free(this_object->bssid);
            this_object->bssid = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->bssid, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_bssid = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
report_event_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  ReportEvent * this_object = REPORT_EVENT(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "ReportEvent", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "eventId", T_I16, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i16 (protocol, this_object->eventId, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "eventLibId", T_I16, 2, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i16 (protocol, this_object->eventLibId, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "timeNow", T_I64, 3, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i64 (protocol, this_object->timeNow, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "eventInfo", T_STRING, 4, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->eventInfo, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "eventDesc", T_STRING, 5, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->eventDesc, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "mac", T_STRING, 6, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->mac, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "peerMac", T_STRING, 7, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->peerMac, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "proberMac", T_STRING, 8, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->proberMac, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "proberIp", T_STRING, 9, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->proberIp, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "proberPort", T_STRING, 10, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->proberPort, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "channel", T_I16, 11, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i16 (protocol, this_object->channel, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "signal", T_I16, 12, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i16 (protocol, this_object->signal, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "band", T_I16, 13, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i16 (protocol, this_object->band, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "ssid", T_STRING, 14, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->ssid, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "bssid", T_STRING, 15, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->bssid, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
report_event_set_property (GObject *object,
                           guint property_id,
                           const GValue *value,
                           GParamSpec *pspec)
{
  ReportEvent *self = REPORT_EVENT (object);

  switch (property_id)
  {
    case PROP_REPORT_EVENT_EVENT_ID:
      self->eventId = g_value_get_int (value);
      self->__isset_eventId = TRUE;
      break;

    case PROP_REPORT_EVENT_EVENT_LIB_ID:
      self->eventLibId = g_value_get_int (value);
      self->__isset_eventLibId = TRUE;
      break;

    case PROP_REPORT_EVENT_TIME_NOW:
      self->timeNow = g_value_get_int64 (value);
      self->__isset_timeNow = TRUE;
      break;

    case PROP_REPORT_EVENT_EVENT_INFO:
      if (self->eventInfo != NULL)
        g_free (self->eventInfo);
      self->eventInfo = g_value_dup_string (value);
      self->__isset_eventInfo = TRUE;
      break;

    case PROP_REPORT_EVENT_EVENT_DESC:
      if (self->eventDesc != NULL)
        g_free (self->eventDesc);
      self->eventDesc = g_value_dup_string (value);
      self->__isset_eventDesc = TRUE;
      break;

    case PROP_REPORT_EVENT_MAC:
      if (self->mac != NULL)
        g_free (self->mac);
      self->mac = g_value_dup_string (value);
      self->__isset_mac = TRUE;
      break;

    case PROP_REPORT_EVENT_PEER_MAC:
      if (self->peerMac != NULL)
        g_free (self->peerMac);
      self->peerMac = g_value_dup_string (value);
      self->__isset_peerMac = TRUE;
      break;

    case PROP_REPORT_EVENT_PROBER_MAC:
      if (self->proberMac != NULL)
        g_free (self->proberMac);
      self->proberMac = g_value_dup_string (value);
      self->__isset_proberMac = TRUE;
      break;

    case PROP_REPORT_EVENT_PROBER_IP:
      if (self->proberIp != NULL)
        g_free (self->proberIp);
      self->proberIp = g_value_dup_string (value);
      self->__isset_proberIp = TRUE;
      break;

    case PROP_REPORT_EVENT_PROBER_PORT:
      if (self->proberPort != NULL)
        g_free (self->proberPort);
      self->proberPort = g_value_dup_string (value);
      self->__isset_proberPort = TRUE;
      break;

    case PROP_REPORT_EVENT_CHANNEL:
      self->channel = g_value_get_int (value);
      self->__isset_channel = TRUE;
      break;

    case PROP_REPORT_EVENT_SIGNAL:
      self->signal = g_value_get_int (value);
      self->__isset_signal = TRUE;
      break;

    case PROP_REPORT_EVENT_BAND:
      self->band = g_value_get_int (value);
      self->__isset_band = TRUE;
      break;

    case PROP_REPORT_EVENT_SSID:
      if (self->ssid != NULL)
        g_free (self->ssid);
      self->ssid = g_value_dup_string (value);
      self->__isset_ssid = TRUE;
      break;

    case PROP_REPORT_EVENT_BSSID:
      if (self->bssid != NULL)
        g_free (self->bssid);
      self->bssid = g_value_dup_string (value);
      self->__isset_bssid = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
report_event_get_property (GObject *object,
                           guint property_id,
                           GValue *value,
                           GParamSpec *pspec)
{
  ReportEvent *self = REPORT_EVENT (object);

  switch (property_id)
  {
    case PROP_REPORT_EVENT_EVENT_ID:
      g_value_set_int (value, self->eventId);
      break;

    case PROP_REPORT_EVENT_EVENT_LIB_ID:
      g_value_set_int (value, self->eventLibId);
      break;

    case PROP_REPORT_EVENT_TIME_NOW:
      g_value_set_int64 (value, self->timeNow);
      break;

    case PROP_REPORT_EVENT_EVENT_INFO:
      g_value_set_string (value, self->eventInfo);
      break;

    case PROP_REPORT_EVENT_EVENT_DESC:
      g_value_set_string (value, self->eventDesc);
      break;

    case PROP_REPORT_EVENT_MAC:
      g_value_set_string (value, self->mac);
      break;

    case PROP_REPORT_EVENT_PEER_MAC:
      g_value_set_string (value, self->peerMac);
      break;

    case PROP_REPORT_EVENT_PROBER_MAC:
      g_value_set_string (value, self->proberMac);
      break;

    case PROP_REPORT_EVENT_PROBER_IP:
      g_value_set_string (value, self->proberIp);
      break;

    case PROP_REPORT_EVENT_PROBER_PORT:
      g_value_set_string (value, self->proberPort);
      break;

    case PROP_REPORT_EVENT_CHANNEL:
      g_value_set_int (value, self->channel);
      break;

    case PROP_REPORT_EVENT_SIGNAL:
      g_value_set_int (value, self->signal);
      break;

    case PROP_REPORT_EVENT_BAND:
      g_value_set_int (value, self->band);
      break;

    case PROP_REPORT_EVENT_SSID:
      g_value_set_string (value, self->ssid);
      break;

    case PROP_REPORT_EVENT_BSSID:
      g_value_set_string (value, self->bssid);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
report_event_instance_init (ReportEvent * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->eventId = 0;
  object->__isset_eventId = FALSE;
  object->eventLibId = 0;
  object->__isset_eventLibId = FALSE;
  object->timeNow = 0;
  object->__isset_timeNow = FALSE;
  object->eventInfo = NULL;
  object->__isset_eventInfo = FALSE;
  object->eventDesc = NULL;
  object->__isset_eventDesc = FALSE;
  object->mac = NULL;
  object->__isset_mac = FALSE;
  object->peerMac = NULL;
  object->__isset_peerMac = FALSE;
  object->proberMac = NULL;
  object->__isset_proberMac = FALSE;
  object->proberIp = NULL;
  object->__isset_proberIp = FALSE;
  object->proberPort = NULL;
  object->__isset_proberPort = FALSE;
  object->channel = 0;
  object->__isset_channel = FALSE;
  object->signal = 0;
  object->__isset_signal = FALSE;
  object->band = 0;
  object->__isset_band = FALSE;
  object->ssid = NULL;
  object->__isset_ssid = FALSE;
  object->bssid = NULL;
  object->__isset_bssid = FALSE;
}

static void 
report_event_finalize (GObject *object)
{
  ReportEvent *tobject = REPORT_EVENT (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->eventInfo != NULL)
  {
    g_free(tobject->eventInfo);
    tobject->eventInfo = NULL;
  }
  if (tobject->eventDesc != NULL)
  {
    g_free(tobject->eventDesc);
    tobject->eventDesc = NULL;
  }
  if (tobject->mac != NULL)
  {
    g_free(tobject->mac);
    tobject->mac = NULL;
  }
  if (tobject->peerMac != NULL)
  {
    g_free(tobject->peerMac);
    tobject->peerMac = NULL;
  }
  if (tobject->proberMac != NULL)
  {
    g_free(tobject->proberMac);
    tobject->proberMac = NULL;
  }
  if (tobject->proberIp != NULL)
  {
    g_free(tobject->proberIp);
    tobject->proberIp = NULL;
  }
  if (tobject->proberPort != NULL)
  {
    g_free(tobject->proberPort);
    tobject->proberPort = NULL;
  }
  if (tobject->ssid != NULL)
  {
    g_free(tobject->ssid);
    tobject->ssid = NULL;
  }
  if (tobject->bssid != NULL)
  {
    g_free(tobject->bssid);
    tobject->bssid = NULL;
  }
}

static void
report_event_class_init (ReportEventClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = report_event_read;
  struct_class->write = report_event_write;

  gobject_class->finalize = report_event_finalize;
  gobject_class->get_property = report_event_get_property;
  gobject_class->set_property = report_event_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_EVENT_ID,
     g_param_spec_int ("eventId",
                       NULL,
                       NULL,
                       G_MININT16,
                       G_MAXINT16,
                       0,
                       G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_EVENT_LIB_ID,
     g_param_spec_int ("eventLibId",
                       NULL,
                       NULL,
                       G_MININT16,
                       G_MAXINT16,
                       0,
                       G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_TIME_NOW,
     g_param_spec_int64 ("timeNow",
                         NULL,
                         NULL,
                         G_MININT64,
                         G_MAXINT64,
                         0,
                         G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_EVENT_INFO,
     g_param_spec_string ("eventInfo",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_EVENT_DESC,
     g_param_spec_string ("eventDesc",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_MAC,
     g_param_spec_string ("mac",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_PEER_MAC,
     g_param_spec_string ("peerMac",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_PROBER_MAC,
     g_param_spec_string ("proberMac",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_PROBER_IP,
     g_param_spec_string ("proberIp",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_PROBER_PORT,
     g_param_spec_string ("proberPort",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_CHANNEL,
     g_param_spec_int ("channel",
                       NULL,
                       NULL,
                       G_MININT16,
                       G_MAXINT16,
                       0,
                       G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_SIGNAL,
     g_param_spec_int ("signal",
                       NULL,
                       NULL,
                       G_MININT16,
                       G_MAXINT16,
                       0,
                       G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_BAND,
     g_param_spec_int ("band",
                       NULL,
                       NULL,
                       G_MININT16,
                       G_MAXINT16,
                       0,
                       G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_SSID,
     g_param_spec_string ("ssid",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_BSSID,
     g_param_spec_string ("bssid",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));
}

GType
report_event_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (ReportEventClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) report_event_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (ReportEvent),
      0, /* n_preallocs */
      (GInstanceInitFunc) report_event_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "ReportEventType",
                                   &type_info, 0);
  }

  return type;
}

/* constants */

enum _ReportEventServiceReportArgsProperties
{
  PROP_REPORT_EVENT_SERVICE_REPORT_ARGS_0,
  PROP_REPORT_EVENT_SERVICE_REPORT_ARGS_E
};

/* reads a report_event_service_report_args object */
static gint32
report_event_service_report_args_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  ReportEventServiceReportArgs * this_object = REPORT_EVENT_SERVICE_REPORT_ARGS(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_STRUCT)
        {
          if ((ret = thrift_struct_read (THRIFT_STRUCT (this_object->e), protocol, error)) < 0)
          {
            return -1;
          }
          xfer += ret;
          this_object->__isset_e = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
report_event_service_report_args_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  ReportEventServiceReportArgs * this_object = REPORT_EVENT_SERVICE_REPORT_ARGS(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "ReportEventServiceReportArgs", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "e", T_STRUCT, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_struct_write (THRIFT_STRUCT (this_object->e), protocol, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
report_event_service_report_args_set_property (GObject *object,
                                               guint property_id,
                                               const GValue *value,
                                               GParamSpec *pspec)
{
  ReportEventServiceReportArgs *self = REPORT_EVENT_SERVICE_REPORT_ARGS (object);

  switch (property_id)
  {
    case PROP_REPORT_EVENT_SERVICE_REPORT_ARGS_E:
      if (self->e != NULL)
        g_object_unref (self->e);
      self->e = g_value_dup_object (value);
      self->__isset_e = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
report_event_service_report_args_get_property (GObject *object,
                                               guint property_id,
                                               GValue *value,
                                               GParamSpec *pspec)
{
  ReportEventServiceReportArgs *self = REPORT_EVENT_SERVICE_REPORT_ARGS (object);

  switch (property_id)
  {
    case PROP_REPORT_EVENT_SERVICE_REPORT_ARGS_E:
      g_value_set_object (value, self->e);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
report_event_service_report_args_instance_init (ReportEventServiceReportArgs * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->e = g_object_new (TYPE_REPORT_EVENT, NULL);
  object->__isset_e = FALSE;
}

static void 
report_event_service_report_args_finalize (GObject *object)
{
  ReportEventServiceReportArgs *tobject = REPORT_EVENT_SERVICE_REPORT_ARGS (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->e != NULL)
  {
    g_object_unref(tobject->e);
    tobject->e = NULL;
  }
}

static void
report_event_service_report_args_class_init (ReportEventServiceReportArgsClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = report_event_service_report_args_read;
  struct_class->write = report_event_service_report_args_write;

  gobject_class->finalize = report_event_service_report_args_finalize;
  gobject_class->get_property = report_event_service_report_args_get_property;
  gobject_class->set_property = report_event_service_report_args_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_REPORT_EVENT_SERVICE_REPORT_ARGS_E,
     g_param_spec_object ("e",
                         NULL,
                         NULL,
                         TYPE_REPORT_EVENT,
                         G_PARAM_READWRITE));
}

GType
report_event_service_report_args_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (ReportEventServiceReportArgsClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) report_event_service_report_args_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (ReportEventServiceReportArgs),
      0, /* n_preallocs */
      (GInstanceInitFunc) report_event_service_report_args_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "ReportEventServiceReportArgsType",
                                   &type_info, 0);
  }

  return type;
}

/* reads a report_event_service_report_result object */
static gint32
report_event_service_report_result_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  ReportEventServiceReportResult * this_object = REPORT_EVENT_SERVICE_REPORT_RESULT(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
report_event_service_report_result_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  ReportEventServiceReportResult * this_object = REPORT_EVENT_SERVICE_REPORT_RESULT(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "ReportEventServiceReportResult", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void 
report_event_service_report_result_instance_init (ReportEventServiceReportResult * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
}

static void 
report_event_service_report_result_finalize (GObject *object)
{
  ReportEventServiceReportResult *tobject = REPORT_EVENT_SERVICE_REPORT_RESULT (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
}

static void
report_event_service_report_result_class_init (ReportEventServiceReportResultClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = report_event_service_report_result_read;
  struct_class->write = report_event_service_report_result_write;

  gobject_class->finalize = report_event_service_report_result_finalize;
}

GType
report_event_service_report_result_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (ReportEventServiceReportResultClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) report_event_service_report_result_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (ReportEventServiceReportResult),
      0, /* n_preallocs */
      (GInstanceInitFunc) report_event_service_report_result_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "ReportEventServiceReportResultType",
                                   &type_info, 0);
  }

  return type;
}

